scan_paths:
  - /mnt/user/data

# Exclude patterns are applied during result parsing (not during scan)
# Patterns use glob syntax: * matches any characters, ? matches single character
exclude_patterns:
  - "*.tmp"
  - "*/.Trash-*"
  - "*/System Volume Information/*"

path_preferences:
  - pattern: "/mnt/user/data/media/*"
    priority: 1
  - pattern: "/mnt/user/data/downloads/*"
    priority: 2

rmlint_options:
  algorithm: "xxhash"

safety:
  verify_after_hardlink: true
  keep_backups: false
  # Cross-disk deduplication options:
  # - "skip": Skip cross-disk duplicates (safest, no space savings)
  # - "delete_duplicate": Delete non-preferred duplicates (saves space, loses redundancy)
  # - "manual_review": Mark all cross-disk for manual review
  cross_disk_action: "manual_review"  # Default: manual_review

